'use strict';
// The send shape, locked: an edit resend goes out as the page built it.
//
// POSTMORTEM.md records the timing table that used to be defended here. The
// same five-image message and prompt, one difference removed at a time:
//
//   action  attachments              conversation tuple    time
//   2       page's own references    present whole         88.3s
//   null    mixed contrib, 9 elems   present whole         79.9s
//   null    all contrib, 2 elems     present whole         58.0s
//   null    all contrib, 2 elems     cleared               47.1s
//   null    all contrib, 2 elems     id kept, resume null  24.2s
//
// Every row under the first loses the turn on message #0. The action code is
// what makes the server file the send as a revision of the edited turn; with
// it cleared the server appends a new turn instead, and on a message with no
// parent a reload shows the original turn, with every image generated by the
// resend gone from the conversation and from the library. Each of the faster
// rows was measured on a message that had a parent, where the new turn is the
// one a reload shows, so each looked right. The trace of 2026-09-10 (ten sends
// against one conversation, 06:59 to 09:53) shows the page's own body carrying
// action 2 every time, with and without a resume blob in the tuple, and the
// script clearing it every time.
//
// So nothing about the send is chosen any more. The action stays 2, the
// conversation tuple is not touched, and an existing attachment goes out with
// the reference it already holds - the server's token, or a contrib this
// document minted - and is re-uploaded only when that reference is one the
// server no longer honours. What is guarded is that nothing else reaches the
// wire.
//
// Run: node tests/send-shape.test.js

const fs = require('fs');
const path = require('path');
const assert = require('assert');

const BUILT = path.join(__dirname, '..', 'gemini-imgen-enhancer.user.js');
const source = fs.readFileSync(BUILT, 'utf8');

function extract(name) {
  const at = source.indexOf('\n  function ' + name + '(');
  if (at === -1) throw new Error('not found in the built script: ' + name);
  const open = source.indexOf('{', at);
  let depth = 0;
  for (let j = open; j < source.length; j++) {
    if (source[j] === '{') depth++;
    else if (source[j] === '}') {
      depth--;
      if (depth === 0) return source.slice(at + 1, j + 1);
    }
  }
  throw new Error('unbalanced braces reading ' + name);
}

const state = { refusals: [], work: {} };
const names = ['guardSendShape', 'isEditResend', 'applyPlanTo', 'settleExisting',
  'attReusable', 'planIsReady'];
const body = names.map(extract).join('\n') + '\n; return { ' + names.join(', ') + ' };';
const api = new Function('PROMPT_TUPLE', 'ATTACHMENTS', 'ACTION_INDEX', 'ACTION_EDIT_RESEND',
  'CONVERSATION_INDEX', 'RESUME_INDEX', 'work', 'attClass', 'dbg', 'attShape', 'refuseSend',
  'say', 'LOG_IMG', body)(
    0, 3, 72, 2, 2, 9,
    state.work,
    (att) => (Array.isArray(att) && att[0] && typeof att[0][0] === 'string'
      && att[0][0].indexOf('/contrib_service/') === 0
      ? (att.__stale ? 'contrib-stale' : 'contrib-live')
      : (Array.isArray(att) && att.length >= 3 && typeof att[2] === 'string' ? 'token' : 'other')),
    function () { },
    (list) => (Array.isArray(list) ? list.map((a) => a[1]).join(', ') : String(list)),
    function (why) { state.refusals.push(why); return null; },
    function () { }, '[gpie]');

const CONV = 'c_00112233445566778899aabbccddeeff';

function contrib(name) {
  return [['/contrib_service/ttl_1d/' + name, 1, null, 'image/jpeg'], name];
}

function stale(name) {
  const t = contrib(name);
  t.__stale = true;
  return t;
}

function token(name) {
  return [[null, 1, 1, 'image/jpeg'], name, '$AXzLiR' + name];
}

// An edit resend as Gemini builds one. The conversation tuple carries the id;
// the resume blob is there on some edits and not on others, and the previous
// turn's r_ and rc_ are empty on message #0.
function editResend(attachments, tuple) {
  const inner = new Array(97).fill(null);
  inner[0] = ['prompt text', 0, null, attachments, null, null, 0, null, null, []];
  inner[2] = tuple || [CONV, '', '', null, null, null, null, null, null, 'RESUME-BLOB-PRESENT'];
  inner[72] = 2;
  return inner;
}

// A plan as makePlan leaves one after settleExisting has run over it: entries
// positional, base the record's list or null for a message never resent.
function planFor(base, count) {
  const p = {
    index: 0, retry: false, blocked: null, base: base,
    originalCount: count == null ? (base ? base.length : 0) : count,
    entries: []
  };
  for (let i = 0; i < p.originalCount; i++) p.entries.push({ kind: 'existing', index: i });
  api.settleExisting(p);
  return p;
}

let failures = 0;
function it(what, fn) {
  state.refusals = [];
  try {
    fn();
    console.log('  ok   ' + what);
  } catch (err) {
    failures++;
    console.log('  FAIL ' + what + '\n       ' + (err && err.message));
  }
}

console.log('send shape');

it('the action stays 2: the send is the edit resend the page built', function () {
  const inner = editResend([token('a.jpg')]);
  assert.strictEqual(api.guardSendShape(inner, inner[0][3], { index: 0 }), true);
  assert.strictEqual(inner[72], 2,
    'null files the send as a new turn, and on message #0 the reload shows the original');
});

it('the conversation tuple goes out whole, resume blob included', function () {
  const inner = editResend([token('a.jpg')]);
  api.guardSendShape(inner, inner[0][3], { index: 0 });
  assert.strictEqual(inner[2][9], 'RESUME-BLOB-PRESENT');
  assert.strictEqual(inner[2][0], CONV,
    'clearing the tuple files the turn under a conversation the server opens for itself');
});

it('a tuple the page built without a resume blob is left alone too', function () {
  const inner = editResend([token('a.jpg')], [CONV, '', '', null, null, null, null, null, null, null]);
  api.guardSendShape(inner, inner[0][3], { index: 0 });
  assert.deepStrictEqual(inner[2], [CONV, '', '', null, null, null, null, null, null, null],
    'the 09:53 send of 2026-09-10 carried no blob and the page still sent it as action 2');
  assert.strictEqual(inner[72], 2);
});

it('the page\'s own references and this document\'s uploads may share a list', function () {
  const inner = editResend([token('a.jpg'), contrib('b.jpg')]);
  assert.strictEqual(api.guardSendShape(inner, inner[0][3], { index: 0 }), true,
    'that is the list the page itself sends after an image is replaced');
  assert.deepStrictEqual(state.refusals, []);
});

it('a contrib the server no longer honours is refused, and the body is left as it was', function () {
  const inner = editResend([token('a.jpg'), stale('b.jpg')]);
  assert.strictEqual(api.guardSendShape(inner, inner[0][3], { index: 0 }), false);
  assert.strictEqual(state.refusals.length, 1);
  assert.strictEqual(inner[72], 2);
});

it('the shape is reported under one name, and there is only one', function () {
  const inner = editResend([token('a.jpg'), contrib('b.jpg')]);
  api.guardSendShape(inner, inner[0][3], { index: 0 });
  assert.strictEqual(state.work.shape, 'edit resend');
  assert.strictEqual(state.work.images, 2);
});

console.log('what an existing entry goes out as');

it('a record of server references is sent as it stands, nothing uploaded', function () {
  const p = planFor([token('a.jpg'), token('b.jpg')]);
  assert.ok(p.entries.every((e) => e.sendAsIs), 'both entries hold a reference the server honours');
  assert.strictEqual(api.planIsReady(p), true, 'and the plan is ready the moment it is made');
  const inner = editResend([token('a.jpg'), token('b.jpg')]);
  assert.strictEqual(api.applyPlanTo(inner, p), true);
  assert.deepStrictEqual(inner[0][3], [token('a.jpg'), token('b.jpg')]);
  assert.strictEqual(inner[0][3][0].length, 3, 'a server reference keeps its three elements');
});

it('a live contrib of this document is sent as it stands too', function () {
  const p = planFor([contrib('a.jpg')]);
  assert.strictEqual(p.entries[0].sendAsIs, true);
  const inner = editResend([token('a.jpg')]);
  assert.strictEqual(api.applyPlanTo(inner, p), true);
  assert.deepStrictEqual(inner[0][3], [contrib('a.jpg')], 'two elements, as uploadFile mints them');
});

it('only a contrib the server no longer honours waits on a re-upload', function () {
  const p = planFor([token('a.jpg'), stale('b.jpg')]);
  assert.strictEqual(p.entries[0].sendAsIs, true);
  assert.strictEqual(p.entries[1].sendAsIs, undefined);
  assert.strictEqual(api.planIsReady(p), false, 'the stale one has nothing to be written from yet');
  p.entries[1].freshAttachment = contrib('b.jpg');
  assert.strictEqual(api.planIsReady(p), true);
  const inner = editResend([token('a.jpg'), token('b.jpg')]);
  assert.strictEqual(api.applyPlanTo(inner, p), true);
  assert.deepStrictEqual(inner[0][3], [token('a.jpg'), contrib('b.jpg')],
    'the honoured reference is kept, the dead one is replaced by the fresh upload');
});

it('a message never resent goes out with the list the page built, read at the send', function () {
  const p = planFor(null, 2);
  assert.ok(p.entries.every((e) => e.sendAsIs), 'no record, so the page\'s list is the reference');
  assert.strictEqual(api.planIsReady(p), true);
  // The page's own tuple, whatever its length: an edit resend is the page's
  // own send, so its form is sent as found.
  const nine = token('a.jpg').concat([null, null, null, null, null, [0]]);
  assert.strictEqual(nine.length, 9);
  const inner = editResend([nine, token('b.jpg')]);
  assert.strictEqual(api.applyPlanTo(inner, p), true);
  assert.deepStrictEqual(inner[0][3], [nine, token('b.jpg')], 'verbatim, tail included');
});

it('a reordered edit writes the record\'s references in the new order', function () {
  const p = planFor([token('a.jpg'), token('b.jpg')]);
  p.entries.reverse();
  const inner = editResend([token('a.jpg'), token('b.jpg')]);
  assert.strictEqual(api.applyPlanTo(inner, p), true);
  assert.deepStrictEqual(inner[0][3], [token('b.jpg'), token('a.jpg')]);
});

it('a new image goes out as the contrib its upload minted', function () {
  const p = planFor([token('a.jpg')]);
  p.entries.push({ kind: 'new', name: 'c.jpg', attachment: contrib('c.jpg') });
  const inner = editResend([token('a.jpg')]);
  assert.strictEqual(api.applyPlanTo(inner, p), true);
  assert.deepStrictEqual(inner[0][3], [token('a.jpg'), contrib('c.jpg')]);
});

it('an entry with nothing to be written from refuses the send', function () {
  const p = planFor([stale('a.jpg')]);
  const inner = editResend([token('a.jpg')]);
  assert.strictEqual(api.applyPlanTo(inner, p), false);
  assert.strictEqual(state.refusals.length, 1);
  assert.ok(/1 of the attachments/.test(state.refusals[0]), state.refusals[0]);
});

it('attReusable is the one reading of "the server still honours this"', function () {
  assert.strictEqual(api.attReusable(token('a.jpg')), true);
  assert.strictEqual(api.attReusable(contrib('a.jpg')), true);
  assert.strictEqual(api.attReusable(stale('a.jpg')), false);
  assert.strictEqual(api.attReusable(null), false);
  assert.strictEqual(api.attReusable(['prompt text', 0]), false);
});

console.log(failures ? '\n' + failures + ' failing' : '\nall passing');
process.exitCode = failures ? 1 : 0;
